name: Trigger Web Repo Webhook

on:
  push:
    branches:
      - master

jobs:
  notify-web-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook on Web Repo
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.WEB_REPO_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/alexander-hurd/Portfolio-Web/dispatches \
          -d '{"event_type":"content-updated"}'
          echo "Triggered webhook on Web Repo"
